version: "3.1"
services:
  rabbit:
    image: rabbitmq:3.9-management
    container_name: rabbitmq-message
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    labels:
      - traefik.backend=message
      - traefik.port=15672
      - traefik.enable=true
